### ISSUE TITLE
Stop the game when win or lose

### ISSUE THREAD

**Issue by alcalyn** [alcalyn/openhex#6]
Currently, when we have conquered the full world, nothing happens.

The game should display an ending screen when there is only one player (player or IA) still alive.

**Comment by alcalyn** [comment]
Fixed by @MattIPv4 in https://github.com/alcalyn/openhex/pull/4

**Comment by MattIPv4** [comment]
I wouldn't consider this fully done. Currently, the game just stops. I think it should really present a popup that says which player won and some stats about the game?

**Comment by alcalyn** [comment]
Sure, I just created https://github.com/alcalyn/openhex/issues/11
